import type { Database, MinuteFormData, PermissionKey } from "@/types/domain";

const permissions: PermissionKey[] = [
  "dashboard.view",
  "users.manage",
  "roles.manage",
  "members.view",
  "members.manage",
  "minutes.view",
  "minutes.manage",
  "missionary.view",
  "missionary.manage",
  "patrol.view",
  "patrol.manage",
  "reports.view",
  "exports.run",
  "audit.view",
];

export function emptyHybridField() {
  return {
    mode: "linked" as const,
    linkedId: "",
    manualValue: "",
  };
}

export function createEmptyMinuteForm(): MinuteFormData {
  return {
    presiding: emptyHybridField(),
    conducting: emptyHybridField(),
    recognitions: "",
    announcements: "",
    attendance: 0,
    conductor: emptyHybridField(),
    accompanist: emptyHybridField(),
    openingHymn: emptyHybridField(),
    openingPrayer: emptyHybridField(),
    releases: "",
    sustainings: "",
    priesthoodAdvancements: "",
    certificates: "",
    confirmations: "",
    childBlessings: "",
    sacramentHymn: emptyHybridField(),
    speaker1: emptyHybridField(),
    speaker2: emptyHybridField(),
    intermediateHymn: emptyHybridField(),
    speaker3: emptyHybridField(),
    closingHymn: emptyHybridField(),
    closingPrayer: emptyHybridField(),
    notes: "",
  };
}

export function createSeedDatabase(): Database {
  const minuteForm = createEmptyMinuteForm();

  minuteForm.presiding = { mode: "linked", linkedId: "member_arthur" };
  minuteForm.conducting = { mode: "linked", linkedId: "member_luiz" };
  minuteForm.recognitions = "Visitantes da Ala Jardim Central e família recém-chegada.";
  minuteForm.announcements = "Mutirão no sábado às 08h e devocional para jovens na sexta.";
  minuteForm.attendance = 164;
  minuteForm.conductor = { mode: "linked", linkedId: "member_joao" };
  minuteForm.accompanist = { mode: "manual", manualValue: "Irmã Paula Nascimento" };
  minuteForm.openingHymn = { mode: "manual", manualValue: "Hino 19 - Graças Damos, Ó Deus" };
  minuteForm.openingPrayer = { mode: "linked", linkedId: "member_daniel" };
  minuteForm.releases = "Desobrigação do irmão Caio do chamado de secretário adjunto.";
  minuteForm.sustainings = "Apoio da irmã Renata como professora das Moças.";
  minuteForm.priesthoodAdvancements = "Avanço de Miguel Santos ao ofício de mestre.";
  minuteForm.certificates = "Entrega de certificado do Seminário para Ana Beatriz.";
  minuteForm.confirmations = "";
  minuteForm.childBlessings = "Bênção da criança Theo Oliveira.";
  minuteForm.sacramentHymn = { mode: "manual", manualValue: "Hino 174 - Ao Partirmos o Pão" };
  minuteForm.speaker1 = { mode: "linked", linkedId: "member_maria" };
  minuteForm.speaker2 = { mode: "linked", linkedId: "member_renata" };
  minuteForm.intermediateHymn = { mode: "manual", manualValue: "Hino 136 - A Oração do Profeta" };
  minuteForm.speaker3 = { mode: "manual", manualValue: "Presidência do Quórum de Élderes" };
  minuteForm.closingHymn = { mode: "manual", manualValue: "Hino 152 - Faze-me, Ó Pai" };
  minuteForm.closingPrayer = { mode: "linked", linkedId: "member_esther" };
  minuteForm.notes = "Preparar confirmação de designações para a próxima semana.";

  return {
    stakes: [{ id: "stake_fortaleza", name: "Estaca Fortaleza Norte" }],
    wards: [
      {
        id: "ward_jardim_central",
        stakeId: "stake_fortaleza",
        name: "Ala Jardim Central",
        city: "Fortaleza",
        state: "CE",
        meetingTime: "09:00",
        bishopric: ["Bispo Arthur Lima", "1º Conselheiro Rafael Souza", "2º Conselheiro Jonas Teixeira"],
        summary: "Ala urbana com forte atuação missionária e calendário semanal intenso.",
      },
      {
        id: "ward_aldeota",
        stakeId: "stake_fortaleza",
        name: "Ala Aldeota",
        city: "Fortaleza",
        state: "CE",
        meetingTime: "13:00",
        bishopric: ["Bispo Marcos Nunes", "1º Conselheiro Davi Costa", "2º Conselheiro Bruno Melo"],
        summary: "Ala secundária usada para demonstrar suporte multi-ala no MVP.",
      },
    ],
    roles: [
      {
        id: "role_admin",
        name: "Administrador",
        description: "Acesso total ao sistema e às permissões.",
        permissions,
      },
      {
        id: "role_bishopric",
        name: "Bispo / Presidência",
        description: "Acesso amplo a membros, atas, missionários e ronda.",
        permissions: permissions.filter((permission) => permission !== "users.manage"),
      },
      {
        id: "role_secretary",
        name: "Secretário",
        description: "Mantém atas, membros e apoio operacional.",
        permissions: [
          "dashboard.view",
          "members.view",
          "members.manage",
          "minutes.view",
          "minutes.manage",
          "missionary.view",
          "patrol.view",
          "audit.view",
        ],
      },
      {
        id: "role_auxiliary",
        name: "Líder Auxiliar",
        description: "Consulta o essencial e atualiza só seu contexto operacional.",
        permissions: [
          "dashboard.view",
          "members.view",
          "missionary.view",
          "missionary.manage",
          "patrol.view",
        ],
      },
      {
        id: "role_viewer",
        name: "Consultivo",
        description: "Consulta áreas liberadas sem editar.",
        permissions: ["dashboard.view", "members.view", "minutes.view", "missionary.view", "patrol.view"],
      },
    ],
    users: [
      {
        id: "user_admin",
        wardId: "ward_jardim_central",
        memberId: "member_arthur",
        name: "Arthur Lima",
        email: "arthur@supperala.local",
        phone: "(85) 99999-1001",
        status: "active",
        roleId: "role_admin",
        permissionOverrides: [],
        createdAt: "2026-03-01T10:00:00.000Z",
        lastAccessAt: "2026-04-20T19:35:00.000Z",
      },
      {
        id: "user_secretary",
        wardId: "ward_jardim_central",
        memberId: "member_luiz",
        name: "Luiz Henrique",
        email: "luiz@supperala.local",
        phone: "(85) 99999-1002",
        status: "active",
        roleId: "role_secretary",
        permissionOverrides: ["missionary.manage"],
        createdAt: "2026-03-08T10:00:00.000Z",
        lastAccessAt: "2026-04-20T18:05:00.000Z",
      },
      {
        id: "user_aux",
        wardId: "ward_jardim_central",
        memberId: "member_maria",
        name: "Maria Clara",
        email: "maria@supperala.local",
        phone: "(85) 99999-1003",
        status: "active",
        roleId: "role_auxiliary",
        permissionOverrides: [],
        createdAt: "2026-03-20T10:00:00.000Z",
        lastAccessAt: "2026-04-19T16:22:00.000Z",
      },
      {
        id: "user_viewer",
        wardId: "ward_jardim_central",
        memberId: "member_esther",
        name: "Esther Almeida",
        email: "esther@supperala.local",
        phone: "(85) 99999-1004",
        status: "active",
        roleId: "role_viewer",
        permissionOverrides: [],
        createdAt: "2026-03-28T10:00:00.000Z",
        lastAccessAt: "2026-04-18T11:10:00.000Z",
      },
    ],
    members: [
      {
        id: "member_arthur",
        wardId: "ward_jardim_central",
        name: "Arthur Lima",
        birthDate: "1983-04-18",
        organization: "Bispado",
        sex: "M",
        sacramentTalkDuration: "15",
        canSpeak: true,
        canPreside: true,
        canConduct: true,
      },
      {
        id: "member_luiz",
        wardId: "ward_jardim_central",
        name: "Luiz Henrique",
        birthDate: "1990-09-12",
        organization: "Secretaria",
        sex: "M",
        sacramentTalkDuration: "10",
        canSpeak: true,
        canPreside: false,
        canConduct: true,
      },
      {
        id: "member_maria",
        wardId: "ward_jardim_central",
        name: "Maria Clara",
        birthDate: "1988-06-01",
        organization: "Sociedade de Socorro",
        sex: "F",
        sacramentTalkDuration: "10",
        canSpeak: true,
        canPreside: false,
        canConduct: false,
      },
      {
        id: "member_renata",
        wardId: "ward_jardim_central",
        name: "Renata Moura",
        birthDate: "1995-11-17",
        organization: "Moças",
        sex: "F",
        sacramentTalkDuration: "5",
        canSpeak: true,
        canPreside: false,
        canConduct: false,
      },
      {
        id: "member_daniel",
        wardId: "ward_jardim_central",
        name: "Daniel Sousa",
        birthDate: "2001-02-14",
        organization: "Rapazes",
        sex: "M",
        sacramentTalkDuration: "5",
        canSpeak: true,
        canPreside: false,
        canConduct: false,
      },
      {
        id: "member_esther",
        wardId: "ward_jardim_central",
        name: "Esther Almeida",
        birthDate: "1998-08-25",
        organization: "Primária",
        sex: "F",
        sacramentTalkDuration: "5",
        canSpeak: false,
        canPreside: false,
        canConduct: false,
      },
    ],
    memberNotes: [
      {
        id: "note_1",
        memberId: "member_maria",
        createdAt: "2026-04-19T17:00:00.000Z",
        createdBy: "user_secretary",
        text: "Confirmou disponibilidade para hospedar sisters no próximo domingo.",
      },
      {
        id: "note_2",
        memberId: "member_daniel",
        createdAt: "2026-04-18T19:00:00.000Z",
        createdBy: "user_admin",
        text: "Aceitou cobrir ronda de quinta em caso de substituição.",
      },
    ],
    sacramentMinutes: [
      {
        id: "minute_1",
        wardId: "ward_jardim_central",
        title: "Reunião Sacramental - Domingo",
        date: "2026-04-19",
        status: "published",
        presidency: "Bispado",
        responsibleUserId: "user_secretary",
        form: minuteForm,
        createdAt: "2026-04-17T13:00:00.000Z",
        updatedAt: "2026-04-19T12:30:00.000Z",
        versionIds: ["version_1", "version_2"],
      },
      {
        id: "minute_2",
        wardId: "ward_jardim_central",
        title: "Reunião Sacramental - Próximo Domingo",
        date: "2026-04-26",
        status: "draft",
        presidency: "Bispado",
        responsibleUserId: "user_secretary",
        form: createEmptyMinuteForm(),
        createdAt: "2026-04-20T12:00:00.000Z",
        updatedAt: "2026-04-20T12:00:00.000Z",
        versionIds: [],
      },
    ],
    minuteVersions: [
      {
        id: "version_1",
        minuteId: "minute_1",
        createdAt: "2026-04-18T13:00:00.000Z",
        createdBy: "user_secretary",
        snapshot: minuteForm,
        status: "draft",
      },
      {
        id: "version_2",
        minuteId: "minute_1",
        createdAt: "2026-04-19T12:30:00.000Z",
        createdBy: "user_admin",
        snapshot: minuteForm,
        status: "published",
      },
    ],
    hymns: [
      { id: "hymn_19", number: "19", title: "Graças Damos, Ó Deus" },
      { id: "hymn_136", number: "136", title: "A Oração do Profeta" },
      { id: "hymn_152", number: "152", title: "Faze-me, Ó Pai" },
      { id: "hymn_174", number: "174", title: "Ao Partirmos o Pão" },
      { id: "hymn_198", number: "198", title: "Eu Necessito de Ti" },
    ],
    missionaryCompanionships: [
      {
        id: "comp_elders_centro",
        wardId: "ward_jardim_central",
        name: "Elders Centro",
        type: "elders",
        area: "Centro",
        members: ["Elder Thompson", "Elder Alves"],
        status: "active",
      },
      {
        id: "comp_sisters_leste",
        wardId: "ward_jardim_central",
        name: "Sisters Leste",
        type: "sisters",
        area: "Leste",
        members: ["Sister Brown", "Sister Carvalho"],
        status: "active",
      },
    ],
    hostHouses: [
      {
        id: "house_1",
        wardId: "ward_jardim_central",
        hostMemberId: "member_maria",
        familyName: "Família Clara",
        address: "Rua do Sol, 440 - Jardim Central",
        phone: "(85) 97777-1001",
        capacity: 8,
        notes: "Pode receber elders e sisters juntas.",
        preferredAvailability: "Domingo e quarta",
      },
      {
        id: "house_2",
        wardId: "ward_jardim_central",
        hostMemberId: "member_esther",
        familyName: "Família Almeida",
        address: "Rua Harmonia, 270 - Jardim Central",
        phone: "(85) 97777-1002",
        capacity: 4,
        notes: "Melhor para uma dupla por vez.",
        preferredAvailability: "Domingo",
      },
    ],
    lunchSchedules: [
      {
        id: "lunch_1",
        wardId: "ward_jardim_central",
        date: "2026-04-21",
        time: "12:30",
        companionshipIds: ["comp_elders_centro", "comp_sisters_leste"],
        hostMemberId: "member_maria",
        notes: "Almoço conjunto após entrevistas.",
        status: "confirmed",
        confirmationStatus: "accepted",
      },
      {
        id: "lunch_2",
        wardId: "ward_jardim_central",
        date: "2026-04-24",
        time: "12:00",
        companionshipIds: ["comp_elders_centro"],
        hostMemberId: "member_esther",
        notes: "Levar sobremesa sem lactose.",
        status: "pending",
        confirmationStatus: "viewed",
      },
    ],
    patrolMembers: [
      {
        id: "patrol_arthur",
        wardId: "ward_jardim_central",
        memberId: "member_arthur",
        name: "Arthur Lima",
        phone: "(85) 96666-1001",
        notes: "Coordena trocas e substituições.",
        active: true,
      },
      {
        id: "patrol_luiz",
        wardId: "ward_jardim_central",
        memberId: "member_luiz",
        name: "Luiz Henrique",
        phone: "(85) 96666-1002",
        notes: "",
        active: true,
      },
      {
        id: "patrol_daniel",
        wardId: "ward_jardim_central",
        memberId: "member_daniel",
        name: "Daniel Sousa",
        phone: "(85) 96666-1003",
        notes: "Prefere quinta e sexta.",
        active: true,
      },
    ],
    patrolSchedules: [
      {
        id: "patrol_schedule_1",
        wardId: "ward_jardim_central",
        date: "2026-04-22",
        sacramentalMemberIds: ["patrol_arthur", "patrol_daniel"],
        classMemberIds: ["patrol_luiz"],
        notes: "Verificar portão lateral.",
        status: "confirmed",
        confirmationStatus: "accepted",
      },
      {
        id: "patrol_schedule_2",
        wardId: "ward_jardim_central",
        date: "2026-04-24",
        sacramentalMemberIds: ["patrol_luiz"],
        classMemberIds: ["patrol_arthur", "patrol_daniel"],
        notes: "",
        status: "scheduled",
        confirmationStatus: "viewed",
      },
    ],
    auditLogs: [
      {
        id: "log_1",
        wardId: "ward_jardim_central",
        createdAt: "2026-04-20T19:35:00.000Z",
        actorUserId: "user_admin",
        action: "LOGIN",
        module: "auth",
        itemLabel: "Arthur Lima",
        summary: "Entrou no sistema e abriu o dashboard.",
      },
      {
        id: "log_2",
        wardId: "ward_jardim_central",
        createdAt: "2026-04-20T17:00:00.000Z",
        actorUserId: "user_secretary",
        action: "UPDATE_MINUTE",
        module: "atas",
        itemLabel: "Reunião Sacramental - Domingo",
        summary: "Atualizou frequência e oradores antes da publicação.",
      },
      {
        id: "log_3",
        wardId: "ward_jardim_central",
        createdAt: "2026-04-20T15:15:00.000Z",
        actorUserId: "user_aux",
        action: "UPDATE_LUNCH",
        module: "missionarios",
        itemLabel: "Família Clara / 21-04-2026",
        summary: "Confirmou almoço compartilhado para elders e sisters.",
      },
    ],
    appPreferences: {
      calendarWeekStartsOn: "sunday",
    },
    session: {
      currentUserId: "user_admin",
      currentWardId: "ward_jardim_central",
    },
  };
}
